name: Lint & Test

on: [push, pull_request]

permissions:
  read-all

defaults:
  run:
    shell: bash

jobs:
  lint:
    # Thanks to black for this rule
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install poetry
      run: pipx install poetry~=1.1.14

    - name: Set up environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: poetry install

    - name: Run pre-commit
      id: pre-commit
      uses: pre-commit/action@v2.0.3
      env:
        SKIP: 'flake8'

    # Run flake8 and have it format the linting errors in the format of
    # the GitHub Workflow command to register error annotations. This
    # means that our flake8 output is automatically added as an error
    # annotation to both the run result and in the "Files" tab of a
    # pull request.
    #
    # Format used:
    # ::error file={filename},line={line},col={col}::{message}
    - name: Run flake8
      id: flake8
      if: always() && (steps.pre-commit.outcome == 'success' || steps.pre-commit.outcome == 'failure')
      run: "poetry run flake8 \
      --format='::error file=%(path)s,line=%(row)d,col=%(col)d::\
      [flake8] %(code)s: %(text)s'"
